import { Inter, DM_Serif_Text } from "next/font/google";
import "./globals.css";
import Header from "./layout/Header";
import Footer from "./layout/Footer";
import { ToastContainer } from "react-toastify";

// Define the fonts with CSS variables
const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const dmSerifText = DM_Serif_Text({
  variable: "--font-serif",
  weight: "400", // Serif font usually used for headings or display text
  subsets: ["latin"],
});

export const metadata = {
  title: "Church-Praise the Lord",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${dmSerifText.variable} antialiased`}
      >
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
        />
        <Header />
        <main className="pt-[95px] xs:pt-[110px] sm:pt-[130px] md:pt-[130px] lg:pt-[160px]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
